version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    environment:
      APP_ENV: local
      APP_DEBUG: true
      APP_KEY: base64:xWn1uTrhiLwPvZQWhSFAqUlDbraQqwY4ZdmIeSeZR2g=
      DB_HOST: laravel_db
      DB_PORT: 5432
      DB_DATABASE: hotel-manager
      DB_USERNAME: postgres
      DB_PASSWORD: secret

  db:
    image: postgres:17
    container_name: laravel_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: hotel-manager
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: